### ISSUE TITLE
Line number of source should be removed from calculating hash of function

### ISSUE THREAD

**Issue by vsp4** [zommiommy/cache_decorator#1]
Hi

https://github.com/zommiommy/cache_decorator/blob/master/cache_decorator/cache.py#L45

`"source": inspect.getsourcelines(function)`

https://docs.python.org/3/library/inspect.html#inspect.getsourcelines

I see this is used for calculating hash of a function and as getsourcelines returns a tuple of actual source code + line number, so this invalidates cache and recalculates function in many cases even if some other peice of code / function is modified in the original file apart from the concerned cached/memoized function. I don't think this should be expected.

**Comment by zommiommy** [comment]
Hi, thanks for the issue!

The idea behind it was to avoid the problem of loading stale caches, but I get your point.
Maybe we could put this as an optional feature, so that it's not enabled by default.

**Comment by vsp4** [comment]
@zommiommy
Thanks for the fast solve. But i also liked the code of inspecting source code for invalidating caches, so as suggestion wouldn't it be just better to ignore the line numbers only and keep the actual code. 
So something like inspect.getsourcelines(function)[0] would keep the actual piece dropping volatile line numbers

**Comment by zommiommy** [comment]
You are right, updated again, in the 1.3.2 version now the source inspection is done by default but the line number is ignored.
Any other suggestions? I'm happy to help

**Comment by vsp4** [comment]
Thank you very much. No suggestions for now 👍
