### ISSUE TITLE
Unnecessery numpy import

### ISSUE THREAD

**Issue by rafaelkrysciak** [zommiommy/cache_decorator#18]
In the cache.py, there is an import of the insert function from numpy. But the insert function is never used. 
https://github.com/zommiommy/cache_decorator/blob/8750fab9b2612d73e0ac78c852fde1077cb46136/cache_decorator/cache.py#L10

**Comment by zommiommy** [comment]
Thank you, you are right, let me fix it!

**Comment by rafaelkrysciak** [comment]
Wow, that's fast. 🚀 Thank you very much! 🙏
